In [1]:
import time
for count in range(1, 4):
    time.sleep(1)
    print(f"{count}秒経過")

1秒経過
2秒経過
3秒経過


In [2]:
# 外部ライブラリ演習
# 問題1
import time
for count in range(1, 10):
    time.sleep(1)
    if count%3==0:
        print("Python最高!")
    else:
        print(f"{count}秒経過")

1秒経過
2秒経過
Python最高!
4秒経過
5秒経過
Python最高!
7秒経過
8秒経過
Python最高!


In [5]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]
