In [1]:
import time
for count in range(1, 4):
    time.sleep(1)
    print(f"{count}秒経過")

1秒経過
2秒経過
3秒経過


In [2]:
# 外部ライブラリ演習
# 問題1
import time
for count in range(1, 10):
    time.sleep(1)
    if count%3==0:
        print("Python最高!")
    else:
        print(f"{count}秒経過")

1秒経過
2秒経過
Python最高!
4秒経過
5秒経過
Python最高!
7秒経過
8秒経過
Python最高!


In [5]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [9]:
print(f"次元数：{b.ndim}")
print(f"要素数：{b.size}")
print(f"何行何列：{b.shape}")
print(f"要素の型：{b.dtype}")

次元数：2
要素数：6
何行何列：(2, 3)
要素の型：int64


In [10]:
#np.arange(始, 終, 間隔)
print(np.arange(10, 30, 5))

#等間隔な数列を生成(始, 終, 個数)
print(np.linspace(0, np.pi, 10))

[10 15 20 25]
[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


In [12]:
# numpy配列の作り方
# 問題1
import numpy as np
a = np.arange(0, 15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
# 問題2
b = a.reshape(3, 5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [17]:
# 問題3
print(a.)

int64
