In [1]:
import time
for count in range(1, 4):
    time.sleep(1)
    print(f"{count}秒経過")

1秒経過
2秒経過
3秒経過


In [2]:
# 外部ライブラリ演習
# 問題1
import time
for count in range(1, 10):
    time.sleep(1)
    if count%3==0:
        print("Python最高!")
    else:
        print(f"{count}秒経過")

1秒経過
2秒経過
Python最高!
4秒経過
5秒経過
Python最高!
7秒経過
8秒経過
Python最高!


In [5]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [9]:
print(f"次元数：{b.ndim}")
print(f"要素数：{b.size}")
print(f"何行何列：{b.shape}")
print(f"要素の型：{b.dtype}")

次元数：2
要素数：6
何行何列：(2, 3)
要素の型：int64


In [10]:
#np.arange(始, 終, 間隔)
print(np.arange(10, 30, 5))

#等間隔な数列を生成(始, 終, 個数)
print(np.linspace(0, np.pi, 10))

[10 15 20 25]
[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


In [12]:
# numpy配列の作り方
# 問題1
import numpy as np
a = np.arange(0, 15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
# 問題2
b = a.reshape(3, 5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
# 問題3
print(a.shape)
print(b.shape)

(15,)
(3, 5)


In [22]:
b=np.arange(1,13,2).reshape(2,3)
#列ごとの和
print(b.sum(axis=0))
#行中の最小値
print(b.min(axis=1))
#各行までの累積和
print(b.cumsum(axis=0))

[ 8 12 16]
[1 7]
[[ 1  3  5]
 [ 8 12 16]]


In [25]:
# Numpy配列に対する数学的な演算
# 問題1
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
# 問題2
b = a.reshape(2, 5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [32]:
# 問題3
b0 = np.arange(1, 6)
b1 = np.arange(6, 11)
print(b0)
print(b1)
print(f"b0 + b1 = {b0 + b1}")
print(f"b0 - b1 = {b0 - b1}")
print(f"b0 * b1 = {b0 * b1}")
print(f"b0 / b1 = {b0 / b1}")

[1 2 3 4 5]
[ 6  7  8  9 10]
b0 + b1 = [ 7  9 11 13 15]
b0 - b1 = [-5 -5 -5 -5 -5]
b0 * b1 = [ 6 14 24 36 50]
b0 / b1 = [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
